// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { relations } from "drizzle-orm/relations";
import { users, sales, customers, products, saleItems, repairs, cashSessions } from "./db_schema";

export const salesRelations = relations(sales, ({one, many}) => ({
	user: one(users, {
		fields: [sales.userId],
		references: [users.id]
	}),
	customer: one(customers, {
		fields: [sales.customerId],
		references: [customers.id]
	}),
	saleItems: many(saleItems),
}));

export const usersRelations = relations(users, ({many}) => ({
	sales: many(sales),
	repairs: many(repairs),
	cashSessions: many(cashSessions),
}));

export const customersRelations = relations(customers, ({many}) => ({
	sales: many(sales),
	repairs: many(repairs),
}));

export const saleItemsRelations = relations(saleItems, ({one}) => ({
	product: one(products, {
		fields: [saleItems.productId],
		references: [products.id]
	}),
	sale: one(sales, {
		fields: [saleItems.saleId],
		references: [sales.id]
	}),
}));

export const productsRelations = relations(products, ({many}) => ({
	saleItems: many(saleItems),
}));

export const repairsRelations = relations(repairs, ({one}) => ({
	user: one(users, {
		fields: [repairs.technicianId],
		references: [users.id]
	}),
	customer: one(customers, {
		fields: [repairs.customerId],
		references: [customers.id]
	}),
}));

export const cashSessionsRelations = relations(cashSessions, ({one}) => ({
	user: one(users, {
		fields: [cashSessions.userId],
		references: [users.id]
	}),
}));