-- ----------------------------------------------------------------
-- 🛑 DO NOT EDIT THIS FILE!
-- Regenerated by: edgespark pull schema --db
--
-- To modify your database schema (multiple statements in one command):
--   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
--     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
--     CREATE INDEX idx_posts_created ON posts(created_at)"
--
-- To query your database:
--   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
-- ----------------------------------------------------------------

-- TABLES

CREATE TABLE cash_sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES users(id),
  opening_amount INTEGER NOT NULL DEFAULT 0,
  closing_amount INTEGER,
  expected_amount INTEGER,
  difference INTEGER,
  opened_at INTEGER DEFAULT (strftime('%s', 'now')),
  closed_at INTEGER,
  notes TEXT
);

CREATE TABLE customers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  phone TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  first_visit INTEGER DEFAULT (strftime('%s', 'now')),
  total_spent INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER DEFAULT (strftime('%s', 'now'))
);

CREATE TABLE `es_system__auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`is_anonymous` integer DEFAULT false,
	`__internal_a` text,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`last_login_at` integer
);

CREATE TABLE products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sku TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category TEXT NOT NULL CHECK(category IN ('phone', 'accessory', 'component')),
  brand TEXT,
  model TEXT,
  price_purchase INTEGER NOT NULL DEFAULT 0,
  price_sale INTEGER NOT NULL DEFAULT 0,
  stock INTEGER NOT NULL DEFAULT 0,
  alert_threshold INTEGER NOT NULL DEFAULT 5,
  image_url TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at INTEGER DEFAULT (strftime('%s', 'now')),
  updated_at INTEGER DEFAULT (strftime('%s', 'now'))
);

CREATE TABLE repairs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  customer_id INTEGER NOT NULL REFERENCES customers(id),
  device_brand TEXT NOT NULL,
  device_model TEXT NOT NULL,
  device_variant TEXT,
  device_password TEXT,
  physical_state TEXT,
  issue_description TEXT NOT NULL,
  diagnosis TEXT,
  status TEXT NOT NULL DEFAULT 'new' CHECK(status IN ('new', 'diagnostic', 'repair', 'delivered')),
  estimated_cost INTEGER NOT NULL DEFAULT 0,
  final_cost INTEGER,
  technician_id INTEGER REFERENCES users(id),
  promised_date INTEGER,
  delivered_at INTEGER,
  created_at INTEGER DEFAULT (strftime('%s', 'now')),
  updated_at INTEGER DEFAULT (strftime('%s', 'now'))
);

CREATE TABLE sale_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sale_id INTEGER NOT NULL REFERENCES sales(id),
  product_id INTEGER NOT NULL REFERENCES products(id),
  quantity INTEGER NOT NULL DEFAULT 1,
  unit_price INTEGER NOT NULL,
  subtotal INTEGER NOT NULL
);

CREATE TABLE sales (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  customer_id INTEGER REFERENCES customers(id),
  user_id INTEGER NOT NULL REFERENCES users(id),
  total INTEGER NOT NULL DEFAULT 0,
  discount INTEGER NOT NULL DEFAULT 0,
  payment_method TEXT NOT NULL DEFAULT 'cash',
  status TEXT NOT NULL DEFAULT 'completed' CHECK(status IN ('completed', 'cancelled', 'refunded')),
  created_at INTEGER DEFAULT (strftime('%s', 'now'))
);

CREATE TABLE user_roles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  auth_user_id TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'agent',
  created_at INTEGER DEFAULT (strftime('%s', 'now'))
, email TEXT, name TEXT);

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL DEFAULT 'agent' CHECK(role IN ('admin', 'manager', 'agent')),
  created_at INTEGER DEFAULT (strftime('%s', 'now'))
);

-- INDEXS

CREATE INDEX cash_sessions_opened_idx ON cash_sessions(opened_at);

CREATE INDEX cash_sessions_user_idx ON cash_sessions(user_id);

CREATE INDEX customers_phone_idx ON customers(phone);

CREATE UNIQUE INDEX `es_system__auth_user_email_unique` ON `es_system__auth_user` (`email`);

CREATE INDEX products_category_idx ON products(category);

CREATE INDEX products_sku_idx ON products(sku);

CREATE INDEX products_stock_idx ON products(stock);

CREATE INDEX repairs_customer_idx ON repairs(customer_id);

CREATE INDEX repairs_status_idx ON repairs(status);

CREATE INDEX repairs_technician_idx ON repairs(technician_id);

CREATE INDEX sale_items_sale_idx ON sale_items(sale_id);

CREATE INDEX sales_created_idx ON sales(created_at);

CREATE INDEX sales_customer_idx ON sales(customer_id);

CREATE INDEX sales_user_idx ON sales(user_id);

CREATE INDEX user_roles_auth_user_idx ON user_roles(auth_user_id);

CREATE UNIQUE INDEX user_roles_unique_idx ON user_roles(auth_user_id);

CREATE INDEX users_email_idx ON users(email);

CREATE INDEX users_role_idx ON users(role);
