// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, check, text, integer, index, foreignKey } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
	check("users_check_1", sql`role IN ('admin', 'manager', 'agent'`),
	check("products_check_2", sql`category IN ('phone', 'accessory', 'component'`),
	check("sales_check_3", sql`status IN ('completed', 'cancelled', 'refunded'`),
	check("repairs_check_4", sql`status IN ('new', 'diagnostic', 'repair', 'delivered'`),
]);

export const users = sqliteTable("users", {
	id: integer().primaryKey({ autoIncrement: true }),
	name: text().notNull(),
	email: text().notNull(),
	role: text().default("agent").notNull(),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
},
(table) => [
	index("users_role_idx").on(table.role),
	index("users_email_idx").on(table.email),
	check("users_check_1", sql`role IN ('admin', 'manager', 'agent'`),
	check("products_check_2", sql`category IN ('phone', 'accessory', 'component'`),
	check("sales_check_3", sql`status IN ('completed', 'cancelled', 'refunded'`),
	check("repairs_check_4", sql`status IN ('new', 'diagnostic', 'repair', 'delivered'`),
]);

export const products = sqliteTable("products", {
	id: integer().primaryKey({ autoIncrement: true }),
	sku: text().notNull(),
	name: text().notNull(),
	category: text().notNull(),
	brand: text(),
	model: text(),
	pricePurchase: integer("price_purchase").default(0).notNull(),
	priceSale: integer("price_sale").default(0).notNull(),
	stock: integer().default(0).notNull(),
	alertThreshold: integer("alert_threshold").default(5).notNull(),
	imageUrl: text("image_url"),
	isActive: integer("is_active").default(1).notNull(),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
	updatedAt: integer("updated_at").default(sql`(strftime('%s', 'now'))`),
},
(table) => [
	index("products_stock_idx").on(table.stock),
	index("products_category_idx").on(table.category),
	index("products_sku_idx").on(table.sku),
	check("users_check_1", sql`role IN ('admin', 'manager', 'agent'`),
	check("products_check_2", sql`category IN ('phone', 'accessory', 'component'`),
	check("sales_check_3", sql`status IN ('completed', 'cancelled', 'refunded'`),
	check("repairs_check_4", sql`status IN ('new', 'diagnostic', 'repair', 'delivered'`),
]);

export const customers = sqliteTable("customers", {
	id: integer().primaryKey({ autoIncrement: true }),
	phone: text().notNull(),
	name: text().notNull(),
	firstVisit: integer("first_visit").default(sql`(strftime('%s', 'now'))`),
	totalSpent: integer("total_spent").default(0).notNull(),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
},
(table) => [
	index("customers_phone_idx").on(table.phone),
	check("users_check_1", sql`role IN ('admin', 'manager', 'agent'`),
	check("products_check_2", sql`category IN ('phone', 'accessory', 'component'`),
	check("sales_check_3", sql`status IN ('completed', 'cancelled', 'refunded'`),
	check("repairs_check_4", sql`status IN ('new', 'diagnostic', 'repair', 'delivered'`),
]);

export const sales = sqliteTable("sales", {
	id: integer().primaryKey({ autoIncrement: true }),
	customerId: integer("customer_id").references(() => customers.id),
	userId: integer("user_id").notNull().references(() => users.id),
	total: integer().default(0).notNull(),
	discount: integer().default(0).notNull(),
	paymentMethod: text("payment_method").default("cash").notNull(),
	status: text().default("completed").notNull(),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
},
(table) => [
	index("sales_created_idx").on(table.createdAt),
	index("sales_user_idx").on(table.userId),
	index("sales_customer_idx").on(table.customerId),
	check("users_check_1", sql`role IN ('admin', 'manager', 'agent'`),
	check("products_check_2", sql`category IN ('phone', 'accessory', 'component'`),
	check("sales_check_3", sql`status IN ('completed', 'cancelled', 'refunded'`),
	check("repairs_check_4", sql`status IN ('new', 'diagnostic', 'repair', 'delivered'`),
]);

export const saleItems = sqliteTable("sale_items", {
	id: integer().primaryKey({ autoIncrement: true }),
	saleId: integer("sale_id").notNull().references(() => sales.id),
	productId: integer("product_id").notNull().references(() => products.id),
	quantity: integer().default(1).notNull(),
	unitPrice: integer("unit_price").notNull(),
	subtotal: integer().notNull(),
},
(table) => [
	index("sale_items_sale_idx").on(table.saleId),
	check("users_check_1", sql`role IN ('admin', 'manager', 'agent'`),
	check("products_check_2", sql`category IN ('phone', 'accessory', 'component'`),
	check("sales_check_3", sql`status IN ('completed', 'cancelled', 'refunded'`),
	check("repairs_check_4", sql`status IN ('new', 'diagnostic', 'repair', 'delivered'`),
]);

export const repairs = sqliteTable("repairs", {
	id: integer().primaryKey({ autoIncrement: true }),
	customerId: integer("customer_id").notNull().references(() => customers.id),
	deviceBrand: text("device_brand").notNull(),
	deviceModel: text("device_model").notNull(),
	deviceVariant: text("device_variant"),
	devicePassword: text("device_password"),
	physicalState: text("physical_state"),
	issueDescription: text("issue_description").notNull(),
	diagnosis: text(),
	status: text().default("new").notNull(),
	estimatedCost: integer("estimated_cost").default(0).notNull(),
	finalCost: integer("final_cost"),
	technicianId: integer("technician_id").references(() => users.id),
	promisedDate: integer("promised_date"),
	deliveredAt: integer("delivered_at"),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
	updatedAt: integer("updated_at").default(sql`(strftime('%s', 'now'))`),
},
(table) => [
	index("repairs_technician_idx").on(table.technicianId),
	index("repairs_status_idx").on(table.status),
	index("repairs_customer_idx").on(table.customerId),
	check("users_check_1", sql`role IN ('admin', 'manager', 'agent'`),
	check("products_check_2", sql`category IN ('phone', 'accessory', 'component'`),
	check("sales_check_3", sql`status IN ('completed', 'cancelled', 'refunded'`),
	check("repairs_check_4", sql`status IN ('new', 'diagnostic', 'repair', 'delivered'`),
]);

export const cashSessions = sqliteTable("cash_sessions", {
	id: integer().primaryKey({ autoIncrement: true }),
	userId: integer("user_id").notNull().references(() => users.id),
	openingAmount: integer("opening_amount").default(0).notNull(),
	closingAmount: integer("closing_amount"),
	expectedAmount: integer("expected_amount"),
	difference: integer(),
	openedAt: integer("opened_at").default(sql`(strftime('%s', 'now'))`),
	closedAt: integer("closed_at"),
	notes: text(),
},
(table) => [
	index("cash_sessions_opened_idx").on(table.openedAt),
	index("cash_sessions_user_idx").on(table.userId),
	check("users_check_1", sql`role IN ('admin', 'manager', 'agent'`),
	check("products_check_2", sql`category IN ('phone', 'accessory', 'component'`),
	check("sales_check_3", sql`status IN ('completed', 'cancelled', 'refunded'`),
	check("repairs_check_4", sql`status IN ('new', 'diagnostic', 'repair', 'delivered'`),
]);

export const userRoles = sqliteTable("user_roles", {
	id: integer().primaryKey({ autoIncrement: true }),
	authUserId: text("auth_user_id").notNull(),
	role: text().default("agent").notNull(),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
	email: text(),
	name: text(),
},
(table) => [
	uniqueIndex("user_roles_unique_idx").on(table.authUserId),
	index("user_roles_auth_user_idx").on(table.authUserId),
	check("users_check_1", sql`role IN ('admin', 'manager', 'agent'`),
	check("products_check_2", sql`category IN ('phone', 'accessory', 'component'`),
	check("sales_check_3", sql`status IN ('completed', 'cancelled', 'refunded'`),
	check("repairs_check_4", sql`status IN ('new', 'diagnostic', 'repair', 'delivered'`),
]);

