// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED BARREL EXPORT - DO NOT EDIT!
// Regenerated by: edgespark pull schema
//
// Import via: import { tables, buckets } from "@generated";
// ----------------------------------------------------------------

// Database tables namespace
import * as tables from "./db_schema";
export { tables };

// Storage buckets namespace
import * as buckets from "./storage_schema";
export { buckets };

// Combined schema for Drizzle ORM initialization (tables + relations)
// This enables db.query.*.findMany({ with: {...} }) relational queries
import * as _relations from "./db_relations";
export const drizzleSchema = { ...tables, ..._relations };
