// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --storage
//
// To manage storage buckets:
//   - Create:  edgespark storage bucket create <name> "<description>"
//
// Example:
//   edgespark storage bucket create uploads "User uploaded files"
//   edgespark storage bucket create avatars "Profile pictures"
//
// Usage in code:
//   import { buckets } from "@generated";
//   await storage.from(buckets.uploads).put("file.jpg", buffer);
// ----------------------------------------------------------------

import type { BucketDef } from "@sdk/server-types";

// No buckets configured for this environment
